# 列表List
- 一个列表可以储存任意大小的数据集合，你可以理解为他是一个容器

## 先来一个例子爽一爽
![](../Photo/115.png)

In [6]:
a = [1,2,4,'a',1.0,True,[1,2],b]
a

NameError: name 'b' is not defined

## 创建一个列表
- a = [1,2,3,4,5]

In [8]:
import numpy as np
a = [[1,2],[3,4]]
np.array(a)

array([[1, 2],
       [3, 4]])

## 列表的一般操作
![](../Photo/116.png)

In [59]:
a = [1,2,3,[1,2,3]]
b = a[3]
len(b) + len(a) -1

6

In [73]:
def len_():
    a = [1,2,3,[1,2,3]]
    b = a[3]
    c = len(b) + len(a) -1
    return c

In [74]:
len_()

6

In [64]:
a = [[0,1,2],[3,4,5],[6,7,8]]
aa = np.array(a)
aa

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
aa[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [38]:
a = [[0,1,2],[3,4,5],[6,7,8]]

In [49]:
for i in range(2):
    for j in range(2):
        print(a[i][j:j+2])
        print(a[i+1][j:j+2])
        print(a[i+1][j:j+2])
        print('----------')

[0, 1]
[3, 4]
[3, 4]
----------
[1, 2]
[4, 5]
[4, 5]
----------
[3, 4]
[6, 7]
[6, 7]
----------
[4, 5]
[7, 8]
[7, 8]
----------


In [41]:
b = a[0:2][0][0:2]
print(b)
c = a[0:2][1][0:2]
print(c)

[0, 1]
[3, 4]


In [48]:
d = a[0:2][0][1:3]
print(d)
e = a[0:2][1][1:3]
print(e)`

[1, 2]
[4, 5]


In [ ]:
F = a[0:2][0][1:3]
print(F)
g = a[0:2][1][1:3]
print(g)

In [ ]:
d = a[0:2][0][1:3]
print(d)
e = a[0:2][1][1:3]
print(e)

In [ ]:
a = [1,2,4,5,[100,200,300]]
a[4][2]
滑动窗口!

In [34]:
a = [1,2,4,5,[100,200,300]]
a[4][2]

300

In [31]:
a =[1,2,4,5]
a[::2]

[1, 4]

In [30]:
a =[1,2,4,5]
a[3:0:-1]#如果索引取值超过它的值了，就按最后的值取

[5, 4, 2]

In [15]:
a = [1]
b = 5
a * b

[1, 1, 1, 1, 1]

In [9]:
a = 'Jelly'
b = 'lly'
b in a

True

In [10]:
a =[ 1,2,3,'Jelly',1.0]
b = 'lly'
b in a#这就是整体啦

False

In [11]:
a =[ 1,2,3,'Jelly',1.0]
b = 'Jelly'
b in a#这就是整体啦

True

In [12]:
a = [1]
b = [2]
a+b

[1, 2]

In [13]:
a = [1]
b = [2]
b + a#列表只可以和int类型相乘z列表只可以相加。相乘

[2, 1]

In [14]:
a = [1]
b = []
a+b

[1]

# 列表索引操作
- Mylist[index]
- 正序索引，逆序索引
- 列表一定注意越界
- ![](../Photo/117.png)

In [1]:
a = 'str'
len(a)

3

In [2]:
b = [1,2,[1,2,3]]
len(b)

3

In [3]:
b = [1,2,3]
max(b)

3

In [4]:
b = [1,2,3,[1,2,3]]
max(b)#这样不可以，怒可以多级嵌套

TypeError: '>' not supported between instances of 'list' and 'int'

In [6]:
b = [1,2,3,True]
max(b)#True相当于1

3

In [8]:
b = [1,2,0.3]
sum(b)

3.3

In [1]:
a = [2,3]
for i in a:
    print(i)

2
3


In [13]:
b = [1,2,3]
a = [1,2,3]
b == a
b>a

False

In [14]:
Jelly = [1,2,3,4,5]
for i in Jelly:
    print(i)

1
2
3
4
5


In [19]:
Jelly = [2,3,4,5,6]
i=1
while i<6:
    i+=1
    print(i)

2
3
4
5
6


In [22]:
i=0
while i<len(Jelly):
    print(Jelly[i])
    i+=1

2
3
4
5
6


## 列表切片操作
- Mylist[start:end]
- 正序切片，逆序切片

## 列表 +、*、in 、not in

## 使用for循环遍历元素
- for 循环可以遍历一切可迭代元素

## EP：
- 使用while 循环遍历列表

## 列表的比较
- \>,<,>=,<=,==,!=

## 列表生成式
[x for x in range(10)]

In [29]:
import random

In [30]:
K =[random.randint(0,10) for i in range (10)]
K

[1, 6, 8, 3, 8, 7, 10, 0, 10, 3]

In [23]:
U = [x for x in range(10)]
U

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
U = [x+100 for x in range(10)]
U

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]

In [27]:
U = [x for x in range(10) if x%2==0]#不能加else了，只可以加一个简单地条件
U

[0, 2, 4, 6, 8]

In [25]:
a = [1,2,3,4,5,6,7,8]
a

[1, 2, 3, 4, 5, 6, 7, 8]

## 列表的方法
![](../Photo/118.png)

In [33]:
a = 10
b = [100]
b.append(a)
b

[100, 10]

In [46]:
a = [1,2,3,4]
b = [100,200,300,400]
for i in b:
    a.append(i)

In [47]:
a = [1,2,3,4]
b = [100,200,300,400]
a.append(b[1:3])#append只能追加一个
a

[1, 2, 3, 4, [200, 300]]

In [49]:
a = [1,2,2,[2,2],3]
a.count(2)

2

In [56]:
a = [1,2,2,[2,2],3]
for i in a: 
    if type(i) is list:
        print( i.count(2)+a.count(2))

4


In [53]:
a = [1,2,2,[2,2],3]
b = a[3]
b.count(2) + a.count(2)

4

In [58]:
a = [1,2,3,4]
b = [300,400]
b.extend(a)
b

[300, 400, 1, 2, 3, 4]

In [59]:
a+b

[1, 2, 3, 4, 300, 400, 1, 2, 3, 4]

In [60]:
a = [1,2,3,4]
a.index(1)

0

In [63]:
a = [1,2,3,4]
a.insert(0,100)
a

[100, 1, 2, 3, 4]

In [64]:
a = [1,2,3,4]
a.insert(2,100)
a

[1, 2, 100, 3, 4]

In [139]:
b = [1,2,3,4,5,6]
for i in b:
    if i / 2 == 0:
        c = b[i]
        print(c.insert(i,100))

In [140]:
c.insert(i,100)

NameError: name 'c' is not defined

In [183]:
b = [1,2,3,4,5,6]
b

[1, 2, 3, 4, 5, 6]

In [184]:
num = 0
for i in range(len(b)):
    print('***',[i+num])
    if b[i+num] % 2 == 0:
        index_ = b.index(i)
        num2 = i + num
        b.insert(num2,100)
        num += 1
b

*** [0]
*** [1]
*** [3]
*** [4]
*** [6]
*** [7]


[1, 100, 2, 3, 100, 4, 5, 100, 6]

In [168]:
b = [1,2,3,4,5,6]
c = []

In [171]:
for i in b:
    
    if i % 2 == 0 and i !=100 and i not in c:
        c.append(i)
        index_ = b.index(i)
        b.insert(index_,100)
        break
b

[1, 100, 2, 3, 100, 4, 5, 100, 6]

In [194]:
a = [1,1,1,2,3]
a.remove(1)
a

[1, 1, 2, 3]

In [218]:
h = [1,2,1,5,1,7,1,9,1]

In [219]:
for i in h:
    print(i)
    if 1 in i:
        i.remove(1)

1


TypeError: argument of type 'int' is not iterable

In [220]:
h

[1, 2, 1, 5, 1, 7, 1, 9, 1]

## 将字符串分割成列表
- split  按照自定义的内容拆分

## EP:
![](../Photo/119.png)
![](../Photo/120.png)

## 列表的复制
- copy 浅复制
- deepcopy import copy  深复制
- http://www.pythontutor.com/visualize.html#mode=edit

## 列表排序
- sort
- sorted
- 列表的多级排序
    - 匿名函数

## EP：
- 手动排序该列表[5,3,8,0,17]，以升序或者降序

- 1
![](../Photo/121.png)

In [9]:
a = eval(input('输入成绩'))
best=max(a)
for i in a:
    if i>=best-10:
         print(i,'级别A')
    elif i>=best-20:
        print(i,'级别B')
    elif i>=best-30:
        print(i,'级别C')
    elif i>=best-40:
        print(i,'级别D')
    else:
        print('F')

输入成绩40,55,70,58
40 级别C
55 级别B
70 级别A
58 级别B


- 2
![](../Photo/122.png)

In [11]:
a = eval(input('输入一个整数列表'))
print(a[::-1])
a = []
a.reverse()

输入一个整数列表3,4,5
(5, 4, 3)


- 3
![](../Photo/123.png)

In [13]:
a=[5,5,5,7]
for i in a:
    if i>100:
        pass
    else:
        b=a.count(i)       
        print(i,b)            

5 3
5 3
5 3
7 1


- 4
![](../Photo/124.png)

In [14]:
a = [1,2,3,2,3,34,43,5,2,65,]
c = sum(a)/len(a)
num1 = 0
num2 = 0
for i in a:
    if i > c:
        num1 += 1
    if i < c:
        num2 += 1   
print('大于平均数的值为：',num1)
print('小于平均数的值为：',num2)

大于平均数的值为： 3
小于平均数的值为： 7


- 5
![](../Photo/125.png)

In [18]:
import random
U = [random.randint(0,9) for i in range(10) ]
U

[3, 7, 5, 9, 9, 3, 3, 6, 6, 5]

- 6
![](../Photo/126.png)

In [19]:
def num():
    print('输入一个数字列表！')
    a = input(">>")
    b = min(a)
    c = a.index(b)
    print(c)

In [20]:
num()

输入一个数字列表！
>>2,3,4
1


- 7
![](../Photo/127.png)
![](../Photo/128.png)

In [22]:
a=[3,4,5]
random.shuffle(a)
a

[3, 5, 4]

In [23]:
def num():
    a = [1,2,3]  
    random.shuffle(a)
    print(a)

In [24]:
num()

[2, 3, 1]


- 8
![](../Photo/129.png)

In [26]:
def num(): 
    num = [1,2,3,2,1,6,3,4,5,2]
    for i in num:
        if num.count(i)>2:        
            ff = num.remove(i)
            print(ff)
        else:
            pass

In [27]:
num()

None


- 9
![](../Photo/130.png)

- 10
![](../Photo/131.png)

- 11
![](../Photo/132.png)

- 12
![](../Photo/133.png)